INSERT INTO tb_localizacao_aeroporto (cep, cidade, endereco, estado)VALUES ('23456-789', 'Rio de Janeiro', 'Avenida Santos Dumont, 2000', 'RJ');
INSERT INTO tb_localizacao_aeroporto (cep, cidade, endereco, estado)VALUES ('12345-678', 'São Paulo', 'Avenida Paulista, 1000', 'SP');
INSERT INTO tb_aeroporto (capacidade_de_armazenamento_de_combustivel, limite_maximo_aeronaves, nome_aeroporto, permitido_pouso_aeronaves, portoes_de_embarque, fk_localizacao_aeroporto) VALUES (120.5, 75, 'Aeroporto Internacional do Rio de Janeiro', TRUE, '{9, 10, 11, 12, 13, 14}', 1);
INSERT INTO tb_aeroporto (capacidade_de_armazenamento_de_combustivel, limite_maximo_aeronaves, nome_aeroporto, permitido_pouso_aeronaves, portoes_de_embarque, fk_localizacao_aeroporto) VALUES (150.0, 80, 'Aeroporto de São Paulo', TRUE, '{1, 2, 3, 4, 5, 6}', 2);
INSERT INTO tb_tipo_de_carga (carga_fragil, categoria_carga, classificacao_periculosidade, temperatura_da_carga) VALUES (FALSE, 'Perigosa', 'ALTA', 18.0);
INSERT INTO tb_tipo_de_carga (carga_fragil, categoria_carga, classificacao_periculosidade, temperatura_da_carga) VALUES(TRUE, 'Frágil', 'BAIXA', 10.0);
INSERT INTO tb_carga (peso_total_carga, status_da_carga, tipo_de_carga_ticket_da_carga) VALUES (75.0, 'PENDENTE', 1);
INSERT INTO tb_carga (peso_total_carga, status_da_carga, tipo_de_carga_ticket_da_carga) VALUES (50.0, 'ENTREGUE', 2);
INSERT INTO tb_flwaware (destino, numero_da_rota, origem, tempo_estimado_voo) VALUES('Miami', 456, 'Rio de Janeiro', 9.0);
INSERT INTO tb_flwaware (destino, numero_da_rota, origem, tempo_estimado_voo) VALUES('Lisboa', 123, 'São Paulo', 10.5);
INSERT INTO tb_tripulacao (funcao, horas_de_voo, licenciamento, nome, numero_voo) VALUES ('Comissário', 1800, 'Certificado', 'Equipe B', 2345);
INSERT INTO tb_tripulacao (funcao, horas_de_voo, licenciamento, nome, numero_voo) VALUES  ('Piloto', 2500, 'Certificado', 'Equipe A', 2346);
INSERT INTO tb_licenca_de_piloto_anac (data_emissao, data_validade, situacao, tipo_da_licenca) VALUES ('2017-07-15T00:00:00', '2027-07-15T00:00:00', 'ATIVA', 'Comercial');
INSERT INTO tb_licenca_de_piloto_anac (data_emissao, data_validade, situacao, tipo_da_licenca) VALUES ('2015-05-20T00:00:00', '2025-05-20T00:00:00', 'ATIVA', 'Privada');
INSERT INTO tb_piloto (horas_de_voo, nome, status_de_saude, fk_licenca_de_pilotoanac) VALUES (4500, 'Carlos Pereira', 'APTO', 1);
INSERT INTO tb_piloto (horas_de_voo, nome, status_de_saude, fk_licenca_de_pilotoanac) VALUES (3000, 'João Silva', 'APTO', 2);
INSERT INTO tb_aviao (capacidade_maxima_kg, capacidade_maxima_pessoas, fabricante, modelo, fk_fly_aware, fk_piloto, fk_tripulacao, fk_aeroporto) VALUES (19000.0, 160, 'Airbus', 'A320', 1, 1, 1, 1);
INSERT INTO tb_aviao (capacidade_maxima_kg, capacidade_maxima_pessoas, fabricante, modelo, fk_fly_aware, fk_piloto, fk_tripulacao, fk_aeroporto) VALUES (22000.0, 180, 'Boeing', '737', 2, 2, 2, 2);
INSERT INTO tb_passageiro (assento, nome, status_embarque, fk_aviao, fk_carga) VALUES ('14B', 'Maria Costa', 'EMBARCADO', 1, 1);
INSERT INTO tb_passageiro (assento, nome, status_embarque, fk_aviao, fk_carga) VALUES ('12A', 'Pedro Silva', 'CHECK_IN', 2, 2);;