CREATE TABLE TB_LOCALIZACAO_AEROPORTO (
    idLocalizacao SERIAL PRIMARY KEY,
    endereco VARCHAR(75) NOT NULL,
    cidade VARCHAR(25) NOT NULL,
    estado VARCHAR(15) NOT NULL,
    cep VARCHAR(9) NOT NULL
);
